In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt
from keras.layers import Dropout
from keras import regularizers
from keras.utils import to_categorical
import tensorflow as tf

Using TensorFlow backend.


In [2]:
df=pd.read_csv("winequality-red.csv")
df.head(3)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [11]:
df["quality"].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [3]:
dataset=df.values

In [4]:
X=dataset[:,0:11]
Y=dataset[:,11]

In [38]:
min_max_scaler=preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, Y, test_size=0.2)

In [40]:
import keras
y_train_one_hot = keras.utils.to_categorical(Y_train, 10)
y_test_one_hot = keras.utils.to_categorical(Y_test, 10)

In [41]:
y_train_one_hot[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [42]:
print(X_train.shape, X_test.shape, Y_train.shape,  Y_test.shape)

(1279, 11) (320, 11) (1279,) (320,)


In [54]:
#Sigmoid Function (A function which ‘squeezes’ all the initial output to be between 0 and 1)
#ReLU Function (If the initial output is negative, then output 0. If not, do nothing to the initial output)
model = Sequential([
    Dense(32, activation='relu',  kernel_regularizer=regularizers.l2(0.01), input_shape=(11,)),
    Dropout(0.3),
    Dense(32, activation='relu',  kernel_regularizer=regularizers.l2(0.01)),
    Dropout(0.3),
    Dense(10, activation = 'softmax', kernel_regularizer=regularizers.l2(0.01)),
])

In [55]:
model.compile(optimizer='adam',
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])

In [56]:
hist = model.fit(X_train, y_train_one_hot,
          batch_size=32, epochs=500,
                validation_split=0.2)

Train on 1023 samples, validate on 256 samples
Epoch 1/500
1023/1023 [==============================] - 3s 3ms/step - loss: 2.8177 - acc: 0.1691 - val_loss: 2.6403 - val_acc: 0.4023
Epoch 2/500
1023/1023 [==============================] - 0s 277us/step - loss: 2.4652 - acc: 0.3568 - val_loss: 2.1825 - val_acc: 0.4102
Epoch 3/500
1023/1023 [==============================] - 0s 190us/step - loss: 1.9870 - acc: 0.4213 - val_loss: 1.6944 - val_acc: 0.4102
Epoch 4/500
1023/1023 [==============================] - 0s 153us/step - loss: 1.7170 - acc: 0.4203 - val_loss: 1.5470 - val_acc: 0.4102
Epoch 5/500
1023/1023 [==============================] - 0s 221us/step - loss: 1.6327 - acc: 0.4340 - val_loss: 1.4839 - val_acc: 0.4336
Epoch 6/500
1023/1023 [==============================] - 0s 197us/step - loss: 1.5763 - acc: 0.4194 - val_loss: 1.4403 - val_acc: 0.4102
Epoch 7/500
1023/1023 [==============================] - 0s 166us/step - loss: 1.5546 - acc: 0.3969 - val_loss: 1.4069 - val_acc: 0.4

Epoch 60/500
1023/1023 [==============================] - 0s 244us/step - loss: 1.2083 - acc: 0.5699 - val_loss: 1.1175 - val_acc: 0.5898
Epoch 61/500
1023/1023 [==============================] - 0s 258us/step - loss: 1.2130 - acc: 0.5630 - val_loss: 1.1189 - val_acc: 0.5898
Epoch 62/500
1023/1023 [==============================] - 0s 177us/step - loss: 1.2182 - acc: 0.5513 - val_loss: 1.1172 - val_acc: 0.6016
Epoch 63/500
1023/1023 [==============================] - 0s 214us/step - loss: 1.2128 - acc: 0.5425 - val_loss: 1.1185 - val_acc: 0.5938
Epoch 64/500
1023/1023 [==============================] - 0s 175us/step - loss: 1.2225 - acc: 0.5396 - val_loss: 1.1171 - val_acc: 0.5938
Epoch 65/500
1023/1023 [==============================] - 0s 220us/step - loss: 1.2196 - acc: 0.5670 - val_loss: 1.1186 - val_acc: 0.6055
Epoch 66/500
1023/1023 [==============================] - 0s 204us/step - loss: 1.2034 - acc: 0.5533 - val_loss: 1.1216 - val_acc: 0.5859
Epoch 67/500
1023/1023 [==========

1023/1023 [==============================] - 0s 261us/step - loss: 1.1786 - acc: 0.5591 - val_loss: 1.0958 - val_acc: 0.5977
Epoch 120/500
1023/1023 [==============================] - 0s 158us/step - loss: 1.1637 - acc: 0.5591 - val_loss: 1.0996 - val_acc: 0.5938
Epoch 121/500
1023/1023 [==============================] - 0s 162us/step - loss: 1.1862 - acc: 0.5523 - val_loss: 1.0959 - val_acc: 0.6055
Epoch 122/500
1023/1023 [==============================] - 0s 172us/step - loss: 1.1723 - acc: 0.5601 - val_loss: 1.0968 - val_acc: 0.6016
Epoch 123/500
1023/1023 [==============================] - 0s 164us/step - loss: 1.1823 - acc: 0.5758 - val_loss: 1.0959 - val_acc: 0.6055
Epoch 124/500
1023/1023 [==============================] - 0s 160us/step - loss: 1.1759 - acc: 0.5601 - val_loss: 1.0985 - val_acc: 0.5938
Epoch 125/500
1023/1023 [==============================] - 0s 172us/step - loss: 1.1906 - acc: 0.5640 - val_loss: 1.0958 - val_acc: 0.5938
Epoch 126/500
1023/1023 [================

Epoch 178/500
1023/1023 [==============================] - 0s 185us/step - loss: 1.1695 - acc: 0.5699 - val_loss: 1.0854 - val_acc: 0.5938
Epoch 179/500
1023/1023 [==============================] - 0s 152us/step - loss: 1.1804 - acc: 0.5494 - val_loss: 1.0887 - val_acc: 0.5977
Epoch 180/500
1023/1023 [==============================] - 0s 179us/step - loss: 1.1638 - acc: 0.5650 - val_loss: 1.0891 - val_acc: 0.5977
Epoch 181/500
1023/1023 [==============================] - 0s 171us/step - loss: 1.1697 - acc: 0.5552 - val_loss: 1.0864 - val_acc: 0.6016
Epoch 182/500
1023/1023 [==============================] - 0s 152us/step - loss: 1.1788 - acc: 0.5523 - val_loss: 1.0877 - val_acc: 0.5977
Epoch 183/500
1023/1023 [==============================] - 0s 177us/step - loss: 1.1674 - acc: 0.5533 - val_loss: 1.0875 - val_acc: 0.6016
Epoch 184/500
1023/1023 [==============================] - 0s 179us/step - loss: 1.1664 - acc: 0.5630 - val_loss: 1.0893 - val_acc: 0.5898
Epoch 185/500
1023/1023 [==

Epoch 237/500
1023/1023 [==============================] - 0s 257us/step - loss: 1.1577 - acc: 0.5748 - val_loss: 1.0824 - val_acc: 0.6055
Epoch 238/500
1023/1023 [==============================] - 0s 206us/step - loss: 1.1779 - acc: 0.5552 - val_loss: 1.0824 - val_acc: 0.6016
Epoch 239/500
1023/1023 [==============================] - 0s 233us/step - loss: 1.1593 - acc: 0.5748 - val_loss: 1.0844 - val_acc: 0.5938
Epoch 240/500
1023/1023 [==============================] - 0s 208us/step - loss: 1.1622 - acc: 0.5572 - val_loss: 1.0816 - val_acc: 0.6055
Epoch 241/500
1023/1023 [==============================] - 0s 203us/step - loss: 1.1617 - acc: 0.5640 - val_loss: 1.0820 - val_acc: 0.6055
Epoch 242/500
1023/1023 [==============================] - 0s 209us/step - loss: 1.1599 - acc: 0.5621 - val_loss: 1.0824 - val_acc: 0.5938
Epoch 243/500
1023/1023 [==============================] - 0s 171us/step - loss: 1.1716 - acc: 0.5533 - val_loss: 1.0832 - val_acc: 0.6016
Epoch 244/500
1023/1023 [==

1023/1023 [==============================] - 0s 173us/step - loss: 1.1631 - acc: 0.5670 - val_loss: 1.0786 - val_acc: 0.6094
Epoch 296/500
1023/1023 [==============================] - 0s 154us/step - loss: 1.1568 - acc: 0.5582 - val_loss: 1.0803 - val_acc: 0.6016
Epoch 297/500
1023/1023 [==============================] - 0s 192us/step - loss: 1.1656 - acc: 0.5484 - val_loss: 1.0806 - val_acc: 0.6055
Epoch 298/500
1023/1023 [==============================] - 0s 200us/step - loss: 1.1480 - acc: 0.5630 - val_loss: 1.0799 - val_acc: 0.6055
Epoch 299/500
1023/1023 [==============================] - 0s 209us/step - loss: 1.1608 - acc: 0.5611 - val_loss: 1.0784 - val_acc: 0.6055
Epoch 300/500
1023/1023 [==============================] - 0s 222us/step - loss: 1.1584 - acc: 0.5484 - val_loss: 1.0801 - val_acc: 0.5977
Epoch 301/500
1023/1023 [==============================] - 0s 178us/step - loss: 1.1635 - acc: 0.5650 - val_loss: 1.0789 - val_acc: 0.6016
Epoch 302/500
1023/1023 [================

Epoch 354/500
1023/1023 [==============================] - 0s 99us/step - loss: 1.1469 - acc: 0.5679 - val_loss: 1.0740 - val_acc: 0.6055
Epoch 355/500
1023/1023 [==============================] - 0s 132us/step - loss: 1.1411 - acc: 0.5689 - val_loss: 1.0767 - val_acc: 0.5898
Epoch 356/500
1023/1023 [==============================] - 0s 86us/step - loss: 1.1583 - acc: 0.5552 - val_loss: 1.0782 - val_acc: 0.5938
Epoch 357/500
1023/1023 [==============================] - 0s 99us/step - loss: 1.1612 - acc: 0.5582 - val_loss: 1.0752 - val_acc: 0.5977
Epoch 358/500
1023/1023 [==============================] - 0s 116us/step - loss: 1.1562 - acc: 0.5670 - val_loss: 1.0752 - val_acc: 0.6016
Epoch 359/500
1023/1023 [==============================] - 0s 90us/step - loss: 1.1442 - acc: 0.5543 - val_loss: 1.0749 - val_acc: 0.6016
Epoch 360/500
1023/1023 [==============================] - 0s 128us/step - loss: 1.1453 - acc: 0.5709 - val_loss: 1.0763 - val_acc: 0.5898
Epoch 361/500
1023/1023 [======

1023/1023 [==============================] - 0s 86us/step - loss: 1.1549 - acc: 0.5601 - val_loss: 1.0751 - val_acc: 0.5977
Epoch 414/500
1023/1023 [==============================] - 0s 97us/step - loss: 1.1534 - acc: 0.5630 - val_loss: 1.0754 - val_acc: 0.5938
Epoch 415/500
1023/1023 [==============================] - 0s 105us/step - loss: 1.1457 - acc: 0.5709 - val_loss: 1.0759 - val_acc: 0.5938
Epoch 416/500
1023/1023 [==============================] - 0s 107us/step - loss: 1.1505 - acc: 0.5464 - val_loss: 1.0755 - val_acc: 0.6055
Epoch 417/500
1023/1023 [==============================] - 0s 89us/step - loss: 1.1544 - acc: 0.5611 - val_loss: 1.0732 - val_acc: 0.6055
Epoch 418/500
1023/1023 [==============================] - 0s 124us/step - loss: 1.1516 - acc: 0.5621 - val_loss: 1.0780 - val_acc: 0.5938
Epoch 419/500
1023/1023 [==============================] - 0s 201us/step - loss: 1.1444 - acc: 0.5728 - val_loss: 1.0743 - val_acc: 0.6016
Epoch 420/500
1023/1023 [===================

1023/1023 [==============================] - 0s 120us/step - loss: 1.1517 - acc: 0.5660 - val_loss: 1.0789 - val_acc: 0.5859
Epoch 473/500
1023/1023 [==============================] - 0s 99us/step - loss: 1.1471 - acc: 0.5699 - val_loss: 1.0745 - val_acc: 0.6016
Epoch 474/500
1023/1023 [==============================] - 0s 118us/step - loss: 1.1533 - acc: 0.5650 - val_loss: 1.0728 - val_acc: 0.6055
Epoch 475/500
1023/1023 [==============================] - 0s 76us/step - loss: 1.1506 - acc: 0.5621 - val_loss: 1.0740 - val_acc: 0.5938
Epoch 476/500
1023/1023 [==============================] - 0s 161us/step - loss: 1.1508 - acc: 0.5650 - val_loss: 1.0791 - val_acc: 0.5820
Epoch 477/500
1023/1023 [==============================] - 0s 139us/step - loss: 1.1513 - acc: 0.5660 - val_loss: 1.0742 - val_acc: 0.6016
Epoch 478/500
1023/1023 [==============================] - 0s 108us/step - loss: 1.1470 - acc: 0.5601 - val_loss: 1.0758 - val_acc: 0.5898
Epoch 479/500
1023/1023 [==================

In [52]:
# model.evaluate(X_test, Y_test)[1]

In [14]:
y_pred=model.predict(X_test)
print(y_pred)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 5.8404886e-04
  0.0000000e+00 1.0103848e-06]
 [4.0893821e-27 1.4521136e-27 2.2926304e-28 ... 7.7122875e-02
  6.8600464e-01 1.0129469e-18]
 [3.0077965e-25 1.1918955e-25 1.2828211e-25 ... 4.1243204e-01
  5.8638769e-01 7.0220681e-19]
 ...
 [3.7419779e-36 1.7331136e-35 1.1144242e-35 ... 9.0173674e-01
  1.1077287e-25 1.8886672e-37]
 [2.1123347e-21 1.2272596e-20 1.3595671e-20 ... 9.8576087e-01
  8.9218598e-03 6.9335777e-16]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 4.4025193e-05
  0.0000000e+00 0.0000000e+00]]


In [15]:
length=len(y_pred)
for i in range(length):
        y_pred[i]=np.argmax(y_pred[i])
        print(y_pred[i])

[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[4. 4. 4. 4. 4. 4. 4. 4. 4.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[3. 3. 3. 3. 3. 3. 3. 3. 3.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[7. 7. 7. 7. 7. 7. 7. 7. 7.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[6. 6. 6. 6. 6. 6. 6. 6. 6.]
[6. 6. 6. 6. 6

In [16]:
y_pred = y_pred.max(axis=1)

In [17]:
df1 = pd.DataFrame({'Actual': Y_test.flatten(), 'Predicted': y_pred})
df1.head(60)

Actual  Predicted
0      5.0        5.0
1      7.0        7.0
2      6.0        7.0
3      5.0        4.0
4      6.0        6.0
5      6.0        7.0
6      4.0        6.0
7      6.0        6.0
8      6.0        4.0
9      5.0        5.0
10     5.0        5.0
11     5.0        5.0
12     7.0        6.0
13     6.0        6.0
14     5.0        5.0
15     7.0        7.0
16     8.0        7.0
17     6.0        5.0
18     6.0        5.0
19     5.0        5.0
20     5.0        5.0
21     5.0        3.0
22     6.0        6.0
23     6.0        6.0
24     5.0        7.0
25     5.0        5.0
26     6.0        5.0
27     5.0        5.0
28     5.0        5.0
29     5.0        5.0
30     6.0        5.0
31     6.0        5.0
32     5.0        6.0
33     6.0        6.0
34     6.0        6.0
35     4.0        3.0
36     5.0        7.0
37     6.0        5.0
38     6.0        5.0
39     5.0        5.0
40     7.0        7.0
41     7.0        6.0
42     6.0        5.0
43     7.0        6.0
44     6.0        5.0
45     5.0        5.0
46     7.0        8.0
47     7.0        6.0
48     6.0        5.0
49     6.0        6.0
50     5.0        5.0
51     5.0        5.0
52     8.0        7.0
53     7.0        5.0
54     6.0        5.0
55     7.0        7.0
56     6.0        5.0
57     6.0        6.0
58     6.0        6.0
59     5.0        5.0