In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [110]:
dataset=pd.read_csv('Churn_Modelling.csv', index_col=['RowNumber'])
dataset["Gender"]=dataset["Gender"].astype("category")
dataset["Geography"]=dataset["Geography"].astype("category")
dataset

CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                      
1            15634602   Hargrave          619    France  Female   42       2   
2            15647311       Hill          608     Spain  Female   41       1   
3            15619304       Onio          502    France  Female   42       8   
4            15701354       Boni          699    France  Female   39       1   
5            15737888   Mitchell          850     Spain  Female   43       2   
...               ...        ...          ...       ...     ...  ...     ...   
9996         15606229   Obijiaku          771    France    Male   39       5   
9997         15569892  Johnstone          516    France    Male   35      10   
9998         15584532        Liu          709    France  Female   36       7   
9999         15682355  Sabbatini          772   Germany    Male   42       3   
10000        15628319     Walker          792    France  Female   28       4   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   
...              ...            ...        ...             ...   
9996            0.00              2          1               0   
9997        57369.61              1          1               1   
9998            0.00              1          0               1   
9999        75075.31              2          1               0   
10000      130142.79              1          1               0   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0  
...                    ...     ...  
9996              96270.64       0  
9997             101699.77       0  
9998              42085.58       1  
9999              92888.52       1  
10000             38190.78       0  

[10000 rows x 13 columns]

In [111]:
X=dataset.iloc[:, 2:12].values
y=dataset.iloc[:,12].values

In [112]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [113]:
# Apply Label encoding, Convert Categorical Data into number

In [114]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])

In [115]:
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

In [116]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [117]:
# Apply One Hot encoding, A one hot encoding is a representation of categorical variables as binary vectors.

In [118]:
from sklearn.compose import ColumnTransformer
# onehotencoder=OneHotEncoder(categorical_features=[1])
# X=onehotencoder.fit_transform(X).toarray()                                              (Depreciated)

ct = ColumnTransformer([('my_ohe', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)

In [119]:
#To avoid dummy variable trap we should always add one less (n-1) variable 
#then the total number of categories present in the categorical data (n) while adding dummy variables.

In [120]:
X=X[:,1:]

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [123]:
# Feature Scalling

In [124]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [125]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [126]:
# classifier = Sequential([
#     Dense(32, activation='relu', input_shape=(10,)),
#     Dense(32, activation='relu'),
#     Dense(1, activation='sigmoid'),
# ])

In [127]:
# (Input Layer + Outputlayer)/2 <<<<<<<<<<<<<<<<<<<<<<= no of node

In [128]:
classifier=Sequential()
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))
classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

C:\Users\Bilal\Anaconda3\envs\neural-network\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\Bilal\Anaconda3\envs\neural-network\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Bilal\Anaconda3\envs\neural-network\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [129]:
classifier.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']) #if  we have more then 2 varianle in output/dependent variable then we use loss function as categorical_crossentropy

In [130]:
hist = classifier.fit(X_train, y_train,
          batch_size=10, epochs=100) #batch size after no of iteration you want to update the weight

Epoch 1/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4896 - acc: 0.7976
Epoch 2/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4166 - acc: 0.8249
Epoch 3/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4107 - acc: 0.8281: 0s - loss: 0.4318 -
Epoch 4/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4069 - acc: 0.8301
Epoch 5/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4053 - acc: 0.8309
Epoch 6/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4040 - acc: 0.8322: 0s - loss: 0.4026 - acc
Epoch 7/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4029 - acc: 0.8345
Epoch 8/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4016 - acc: 0.8349
Epoch 9/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3999 - acc: 0.8369
Epoch 10/100
8000/8000 [==============================] - 1s 9

8000/8000 [==============================] - 1s 99us/step - loss: 0.3385 - acc: 0.8636
Epoch 76/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3395 - acc: 0.8590: 0s - loss: 0.3251 - acc:
Epoch 77/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.3387 - acc: 0.8607
Epoch 78/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.3392 - acc: 0.8610: 0s - loss: 0.3254 - a
Epoch 79/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.3392 - acc: 0.8591: 0s - loss: 0.3398 - acc: 0.8
Epoch 80/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3397 - acc: 0.8596: 0s - loss: 0.3284 -  - ETA: 0s - loss: 0.3382 - acc: 0.860
Epoch 81/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.3390 - acc: 0.8617: 0s - loss: 0.3392 - acc: 0.861
Epoch 82/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3389 - acc: 0.8595: 0s - loss: 0.3482 - a
Epoch 83/100
8000/8

In [131]:
y_pred=classifier.predict(X_test)

In [132]:
y_pred

array([[0.21163717],
       [0.3174422 ],
       [0.14998934],
       ...,
       [0.1258736 ],
       [0.09994161],
       [0.22124133]], dtype=float32)

In [133]:
y_pred=(y_pred>0.5)

In [137]:
y_pred[0:30]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [138]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [139]:
cm

array([[1491,  104],
       [ 193,  212]], dtype=int64)

In [140]:
accuracy=(1491+212)/(1491+212+104+193)
accuracy

0.8515